version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nebill
permissions:
   - object: /var/www/
     pattern: "**"
     owner: nebill
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: nebill
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: nebill
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
