# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
Rails.application.config.assets.paths << Rails.root.join('vendor', 'assets', 'bower_components')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
Rails.application.config.assets.precompile += %w( view_models/*.js )
Rails.application.config.assets.precompile += %w( pdf/bill.scss )
Rails.application.config.assets.precompile += %w(login/btn_google_*.png)
Rails.application.config.assets.precompile += %w( support/phantomjs-shims.self.js )
Rails.application.config.assets.precompile += %w( jquery.self.js )
Rails.application.config.assets.precompile += %w( jquery_ujs.self.js )
Rails.application.config.assets.precompile += %w( underscore/underscore.self.js )
Rails.application.config.assets.precompile += %w( vue/dist/vue.self.js )
Rails.application.config.assets.precompile += %w( toastr/toastr.self.js )
Rails.application.config.assets.precompile += %w( sortable/Sortable.self.js )
Rails.application.config.assets.precompile += %w( page/page.self.js )
Rails.application.config.assets.precompile += %w( autoNumeric/autoNumeric.self.js )
Rails.application.config.assets.precompile += %w( nested_form_fields.self.js )
Rails.application.config.assets.precompile += %w( core.self.js )
Rails.application.config.assets.precompile += %w( toastr_options.self.js )
Rails.application.config.assets.precompile += %w( parts/dropdown.self.js )
Rails.application.config.assets.precompile += %w( directives/autonumeric.self.js )
Rails.application.config.assets.precompile += %w( mixins/modal.self.js )
Rails.application.config.assets.precompile += %w( mixins/numeric_helper.self.js )
Rails.application.config.assets.precompile += %w( mixins/project_helper.self.js )
Rails.application.config.assets.precompile += %w( components/agreement_approval_list.self.js )
Rails.application.config.assets.precompile += %w( components/agreement_client_list.self.js )
Rails.application.config.assets.precompile += %w( components/agreement_expense_approval_list.self.js )
Rails.application.config.assets.precompile += %w( components/agreement_project_list.self.js )
Rails.application.config.assets.precompile += %w( components/approval_file.self.js )
Rails.application.config.assets.precompile += %w( components/bill_new.self.js )
Rails.application.config.assets.precompile += %w( components/client_file.self.js )
Rails.application.config.assets.precompile += %w( components/client_new.self.js )
Rails.application.config.assets.precompile += %w( components/expense_approval_new.self.js )
Rails.application.config.assets.precompile += %w( components/expense_file.self.js )
Rails.application.config.assets.precompile += %w( components/expense_history.self.js )
Rails.application.config.assets.precompile += %w( components/expense_new.self.js )
Rails.application.config.assets.precompile += %w( components/expense_set_project.self.js )
Rails.application.config.assets.precompile += %w( components/expense_transportation.self.js )
Rails.application.config.assets.precompile += %w( components/file_list.self.js )
Rails.application.config.assets.precompile += %w( components/file_new.self.js )
Rails.application.config.assets.precompile += %w( components/files.self.js )
Rails.application.config.assets.precompile += %w( components/member_list.self.js )
Rails.application.config.assets.precompile += %w( components/partner_member_list.self.js )
Rails.application.config.assets.precompile += %w( components/partner_new.self.js )
Rails.application.config.assets.precompile += %w( components/project_bill_list.self.js )
Rails.application.config.assets.precompile += %w( components/project_detail.self.js )
Rails.application.config.assets.precompile += %w( components/project_file.self.js )
Rails.application.config.assets.precompile += %w( components/project_group_list_item.self.js )
Rails.application.config.assets.precompile += %w( components/project_new.self.js )
Rails.application.config.assets.precompile += %w( components/user_list.self.js )
Rails.application.config.assets.precompile += %w( components/user_member_list.self.js )
Rails.application.config.assets.precompile += %w( components/user_new.self.js )
Rails.application.config.assets.precompile += %w( filters/filter_by_category.self.js )
Rails.application.config.assets.precompile += %w( filters/select_by.self.js )
Rails.application.config.assets.precompile += %w( filters/status_by.self.js )
Rails.application.config.assets.precompile += %w( application.self.js )
Rails.application.config.assets.precompile += %w( spec_helper.self.js )
Rails.application.config.assets.precompile += %w( select_by_spec.self.js )
