default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nebill
  password: nebill
  timeout: 5000
  host: <%= ENV['RAILS_DATABASE_HOST'] || '127.0.0.1' %>

development:
  <<: *default
  database: nebill_development

test:
  <<: *default
  database: nebill_test

staging:
  <<: *default
  database: nebill
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: nebill
  username: <%= ENV['RAILS_DATABASE_USER'] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
